// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5KypRsaxHUn_lB4Ut0VD7NMm3yrCbK5o',
    appId: '1:693608320651:web:2f24cdcb959de526928e8e',
    messagingSenderId: '693608320651',
    projectId: 'attendance-system-69d2d',
    authDomain: 'attendance-system-69d2d.firebaseapp.com',
    storageBucket: 'attendance-system-69d2d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_-snp8jWz6Mi3-hw9ODV2g7OK8xQO3as',
    appId: '1:693608320651:android:eec3b3bd94ced8bb928e8e',
    messagingSenderId: '693608320651',
    projectId: 'attendance-system-69d2d',
    storageBucket: 'attendance-system-69d2d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPBdnbvT2i_PPcaNqnjxaSl9SfbC19NCY',
    appId: '1:693608320651:ios:cbca780603c96119928e8e',
    messagingSenderId: '693608320651',
    projectId: 'attendance-system-69d2d',
    storageBucket: 'attendance-system-69d2d.appspot.com',
    iosBundleId: 'com.zidio.group5.attendanceSystem',
  );
}
